################################################################################
#                                                                              #
#                                    Keypad2                                   #
#                 	 Rotary Encoder and Menu Button Routines                   #
#                                   EE/CS 52                                   #
#                                                                              #
################################################################################


/*
 *  Example Student
 *  EE/CS 52
 *  TA: Dan Pipe-Mazo
 *
 *  File Description:   
 *
 *  Table of Contents:
 *
 *  Revision History:
 *      02/09/2012    Dan Pipe-Mazo			Initial Revision
 *
 */
 
 /*  Local Include Files   */
 //#include "../interfac.m"
// #include "../keypad2.m"
// #include "../intrupt.m"

.section  .text         #start code section
	
/*
 *  key_available
 *
 *  Description:        
 *
 *  Operation:          
 *							
 *  Arguments:          
 *
 *  Return Value:       
 *
 *  Local Variables:    
 *
 *  Shared Variables:   
 *
 *  Global Variables:   
 *
 *  Input:               
 *
 *  Output:             
 *
 *  Error Handling:     
 *
 *  Limitations:        
 *
 *  Algorithms:         
 *  Data Structures:    
 *
 *  Registers Changed:   
 *
 *  Revision History:
 *      02/09/2012    Dan Pipe-Mazo     initial revision
 *
 */

.global key_available
.type key_available,@function

key_available:

#TODO

KeyAvailableDone:
	ret
	
	
/*
 *  getkey
 *
 *  Description:       
 *
 *  Operation:          
 *							
 *  Arguments:          
 *
 *  Return Value:       
 *
 *  Local Variables:    
 *
 *  Shared Variables:   
 *
 *  Global Variables:   
 *
 *  Input:               
 *
 *  Output:             
 *
 *  Error Handling:     
 *
 *  Limitations:        
 *
 *  Algorithms:         
 *  Data Structures:    
 *
 *  Registers Changed:   
 *
 *  Revision History:
 *      02/09/2012    Dan Pipe-Mazo     initial revision
 *
 */

.global getkey
.type getkey,@function

getkey:

#TODO
	
getkeydone:
	ret


.section  .data     #start data section

#TODO
  
